### PR TITLE
[POS Refunds] Fetch Refunds

### PR DESCRIPTION
**Pull request by toupper**
Part of WOOMOB-1786

## Description

To display the Refunds button in the order details when an order has not yet been refunded, we need to fetch the order’s refunds to determine whether any exist.

This PR implements all the logic required to retrieve that information, including the state used to hold and expose it to the UI.

The flow works as follows: when an order is selected, we trigger the refunds retrieval asynchronously without blocking the selection flow. Once the request completes, the refunds state is updated, allowing the view to react accordingly—refreshing the button visibility and, when applicable, displaying the order refunds.

## Test Steps

Please ensure that unit tests run fine. Within the next PR we will implement the actual refunds request to show/hide the Refund button.

---
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+
+struct POSRefundsServiceTests {
+    @Test func providePointOfSaleRefunds_then_calls_remote_with_expected_params() async throws {
+        // Given
+        let remote = MockPOSRefundsRemote()
+        let siteID: Int64 = 123
+        let sut = POSRefundsService(siteID: siteID, refundsRemote: remote)
+        let orderRefunds = [POSOrderRefundCondensed(refundID: 10, formattedTotal: "$22"), POSOrderRefundCondensed(refundID: 20, formattedTotal: "$22")]
+
+        let order = POSOrder(id: 1, number: "1001", dateCreated: Date(), status: .completed,
```
Comment (iamgabrielma) [inline Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift]: Should we extract most of these variables to some setup at the top of the file? IMHO would make the tests more readable, specially since we repeat them across al tests and cannot be sure at first glance if any of the values change: 

ie
```
orderID = 1, 
orderNumber = "1001", 
formattedTotal + " ..." 
```

**Comment by iamgabrielma** [comment]
Just dropping a note about Xcode's odd behavior: While I seem able to build the target, when trying to run the tests I get compilation errors:

Screenshot 2025-12-24 at 10 41 01

Despite that, if I try to clean the build, after a couple of times I'm able to run the tests before I'm hit with the compilation errors again:
```
Test Suite 'Selected tests' started at 2025-12-24 10:49:57.996.
Test Suite 'YosemiteTests.xctest' started at 2025-12-24 10:49:57.996.
Test Suite 'YosemiteTests.xctest' passed at 2025-12-24 10:49:57.996.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' passed at 2025-12-24 10:49:57.996.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
◇ Test run started.
↳ Testing Library Version: 124.4
↳ Target Platform: arm64-apple-ios13.0-simulator
◇ Iteration 1 started.
◇ Suite POSRefundsServiceTests started.
◇ Test providePointOfSaleRefunds_when_remote_succeeds_then_returns_same_count_as_remote() started.
◇ Test providePointOfSaleRefunds_when_remote_fails_then_propagates_remote_error() started.
◇ Test providePointOfSaleRefunds_when_remote_succeeds_then_maps_refund_items_correctly() started.
◇ Test providePointOfSaleRefunds_then_calls_remote_with_expected_params() started.
✔ Test providePointOfSaleRefunds_when_remote_fails_then_propagates_remote_error() passed after 0.012 seconds.
✔ Test providePointOfSaleRefunds_when_remote_succeeds_then_returns_same_count_as_remote() passed after 0.012 seconds.
✔ Test providePointOfSaleRefunds_then_calls_remote_with_expected_params() passed after 0.012 seconds.
✔ Test providePointOfSaleRefunds_when_remote_succeeds_then_maps_refund_items_correctly() passed after 0.012 seconds.
✔ Suite POSRefundsServiceTests passed after 0.012 seconds.
◇ Iteration 1 ended after 0.012 seconds.
✔ Test run with 4 tests passed after 0.012 seconds.
Program ended with exit code: 0
```

I'll continue the review 👀

File: Modules/Sources/TestKit/Testing+Helpers.swift [hunk 2]
```diff
@@ -0,0 +1,15 @@
+import Testing
+
+/// This file gathers helper functions for the new Testing framework
+
+public func waitUntil(
```
Comment (iamgabrielma) [inline Modules/Sources/TestKit/Testing+Helpers.swift]: Is this one needed for any particular reason? We have plenty of `waitUntil` functions already defined in XCTest and the testing framework. 

As a side note, in general we've been trying to remove the reliance on fixed waiting times, as this tends to to drive to test flakiness. Perhaps there is a different way we can mock the test calls to not rely on waiting for a response?

File: Modules/Sources/Networking/Remote/RefundsRemote.swift [hunk 3]
```diff
@@ -145,3 +145,27 @@ public extension RefundsRemote {
...
 }
+
+extension RefundsRemote: POSRefundsRemoteProtocol {
+    public func loadRefunds(for siteID: Int64, by orderID: Int64, with refundIDs: [Int64]) async throws -> [Refund] {
+        return try await withCheckedThrowingContinuation { continuation in
+            loadRefunds(for: siteID, by: orderID, with: refundIDs) { refunds, error in
+                if let error = error {
+                    continuation.resume(throwing: error)
+                } else {
+                    continuation.resume(returning: refunds ?? [])
```
Comment (iamgabrielma) [inline Modules/Sources/Networking/Remote/RefundsRemote.swift:156]: Do you know why does the type returned from the remote is `[Refund]?, Error?`? 

We should either have an array of refunds (which ofc could be empty), or an error. I'm not sure what means for these to be `nil`, and the API reference doesn't say anything about it. 

Out of the scope of this PR since you've only made an async wrapper of what was already there, but worth noting it down for investigating further.

File: Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift [hunk 4]
```diff
@@ -4,11 +4,15 @@ import enum Yosemite.POSOrderListServiceError
 import protocol Yosemite.POSOrderListServiceProtocol
 import protocol Yosemite.POSOrderListFetchStrategyFactoryProtocol
 import protocol Yosemite.POSOrderListFetchStrategy
+import protocol Yosemite.POSRefundsServiceProtocol
+import class Yosemite.POSRefundsService
 import struct Yosemite.POSOrder
+import struct Yosemite.POSRefund
 import struct Yosemite.POSOrderItem
-import struct Yosemite.POSOrderRefund
+import struct Yosemite.POSOrderRefundCondensed
```
Comment (iamgabrielma) [inline Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift]: Not needed:
```suggestion
```

File: Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift [hunk 5]
```diff
@@ -4,11 +4,15 @@ import enum Yosemite.POSOrderListServiceError
 import protocol Yosemite.POSOrderListServiceProtocol
 import protocol Yosemite.POSOrderListFetchStrategyFactoryProtocol
 import protocol Yosemite.POSOrderListFetchStrategy
+import protocol Yosemite.POSRefundsServiceProtocol
+import class Yosemite.POSRefundsService
```
Comment (iamgabrielma) [inline Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift]: Not needed:
```suggestion
```

File: Modules/Sources/NetworkingCore/Remote/POSRefundsRemoteProtocol.swift [hunk 6]
```diff
@@ -0,0 +1,5 @@
+import Foundation
+
+public protocol POSRefundsRemoteProtocol {
+    func loadRefunds(for siteID: Int64, by orderID: Int64, with refundIDs: [Int64]) async throws -> [Refund]
```
Comment (iamgabrielma) [inline Modules/Sources/NetworkingCore/Remote/POSRefundsRemoteProtocol.swift:4]: Some questions: 
- Since it's a `POSRefundsRemote` protocol,  should this interface return a `[POSRefund]` at this stage?
- Should sit in `NetworkingCore/Remote` as it is now, or in `Network/Remote`? The docs are clearly out of date, so I'm not sure, but by checking the project it would seem that networking core is more for tools than app features? (despite orders and pos orders remote being there as well)

File: Modules/Sources/PointOfSale/Models/POSOrdersViewState.swift [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import Foundation
 import struct Yosemite.POSOrder
 import struct Yosemite.POSOrderItem
-import struct Yosemite.POSOrderRefund
+import struct Yosemite.POSOrderRefundCondensed
```
Comment (iamgabrielma) [inline Modules/Sources/PointOfSale/Models/POSOrdersViewState.swift]:
```suggestion
```

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderRefundCondensed.swift [hunk 8]
```diff
@@ -2,7 +2,7 @@ import Foundation
 import struct NetworkingCore.OrderRefundCondensed
 import class WooFoundationCore.CurrencyFormatter
 
-public struct POSOrderRefund: Equatable, Hashable {
+public struct POSOrderRefundCondensed: Equatable, Hashable {
```
Comment (iamgabrielma) [inline Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderRefundCondensed.swift]: Why have we renamed `POSOrderRefund` to `POSOrderRefundCondensed`? This seems to leak the aspect/shape/UI of a refund into the model, and would imply that there is a non-condensed version as well. 

I know we do that in the non-POS side of the app by using `OrderRefundCondensed` in the `Order` model, but perhaps this is not translatable directly to POS and we could use the `POSOrderRefund` model until there is a need to disambiguate it further

I haven't looked much into it, but at first glance I think it could make sense to just make the necessary transformations in the mapper or a close layer from WooCommerce `[Refund]` to POS `[POSOrderRefund]` and then further condensations/transformations can be done at the UI layer.

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundItem.swift [hunk 9]
```diff
@@ -0,0 +1,7 @@
+import Foundation
+
+public struct POSRefundItem: Equatable, Hashable {
+    public let productID: Int64
+    public let variationID: Int64
+    public let quantity: Decimal
```
Comment (iamgabrielma) [inline Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundItem.swift:6]: `OrderItemRefund` does have quantity as `Decimal`, but should we make it `Integer` for POS since we can only refund full units of an item?

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundMapper.swift [hunk 10]
```diff
@@ -0,0 +1,10 @@
+import Foundation
+import struct NetworkingCore.Refund
+
+struct POSRefundMapper {
+    func map(refund: NetworkingCore.Refund) -> POSRefund {
+        let refundItems = refund.items.map { POSRefundItem(productID: $0.productID, variationID: $0.variationID, quantity: $0.quantity) }
```
Comment (iamgabrielma) [inline Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundMapper.swift:6]: The question above regarding making quantity an integer rather than just passing it in.

File: Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift [hunk 11]
```diff
@@ -364,4 +369,86 @@ final class POSOrderListControllerTests {
...
+
+    @Test func selectOrder_then_calls_refunds_service_for_selected_order() async throws {
+        // Given
+        featureFlags.isPointOfSaleRefundsi1Enabled = true
+        let order = MockPOSOrderListService.makeInitialOrders()[0]
+
+        // When
+        await sut.selectOrder(order)
+
+        await waitUntil { [weak self] in
```
Comment (iamgabrielma) [inline Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift]: In the 4 tests that rely on waitUntil in this file, we can use alternative patterns like `withObservationTracking` (`PointOfSaleItemsControllerTests.swift`, `PointOfSaleOrderControllerTests.swift` for examples) which should be more reliable.

File: Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift [hunk 12]
```diff
@@ -364,4 +369,86 @@ final class POSOrderListControllerTests {
...
+            self?.refundsService.spyProvidePointOfSaleRefundsOrder != nil
+        }
+
+        // Then
+        #expect(refundsService.spyProvidePointOfSaleRefundsOrder == order)
+    }
+
+    @Test func selectOrder_then_updates_refunds_state_with_loading() async throws {
```
Comment (iamgabrielma) [inline Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift:387]: This test has no assertion, will always pass no matter the result.

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift [hunk 13]
```diff
@@ -0,0 +1,173 @@
...
+        let sut = POSRefundsService(siteID: 123, refundsRemote: remote)
+
+        struct TestError: Error {}
+        remote.result = .failure(TestError())
+
+        let order = POSOrder(id: 1, number: "1001", dateCreated: Date(), status: .completed,
+                             formattedTotal: "$10.00", formattedSubtotal: "$10.00", customerEmail: "test1@example.com",
+                             paymentMethodTitle: "Credit Card", lineItems: [],
+                             refunds: [], formattedDiscountTotal: nil, formattedTotalTax: "$0.00",
+                             formattedPaymentTotal: "$10.00", formattedNetAmount: nil)
```
Comment (iamgabrielma) [inline Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift]: Question: 
- Is it expected to pass with formattedTotal = $22 in the refund, but $10 in the order? Shouldn't it fail because the refund is higher?
- What's the expectation of `formattedNetAmount` here? Since in refunds we only `formattedTotal` and have no reference for net? I'm assuming taxes need to be handled at some point as well here, as are part of the refunded amount.

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift [hunk 14]
```diff
@@ -0,0 +1,173 @@
...
+        // Then
+        do {
+            _ = try await sut.providePointOfSaleRefunds(for: order)
+            Issue.record("Expected error to be thrown")
+        } catch {
+            #expect(error is TestError)
+        }
+    }
+
+    @Test func providePointOfSaleRefunds_when_remote_succeeds_then_returns_same_count_as_remote() async throws {
```
Comment (iamgabrielma) [inline Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift:45]: I would expect this test to fail in the remote since we're calling `MockRefunds.sampleRefund()` twice, hence they have the same refund ID = 0. AFAU we should handle both cases at this layer or in the networking one (remote failure and remote success)

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift [hunk 15]
```diff
@@ -0,0 +1,173 @@
...
+        // Then
+        #expect(refunds.count == 2)
+    }
+
+    @Test func providePointOfSaleRefunds_when_remote_succeeds_then_maps_refund_items_correctly() async throws {
+        // Given
+        let remote = MockPOSRefundsRemote()
+        let sut = POSRefundsService(siteID: 123, refundsRemote: remote)
+
+        let item1 = MockRefunds.sampleRefundItem(productID: 111, variationID: 222, quantity: 2)
```
Comment (iamgabrielma) [inline Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift:69]: Same as above, I would think this test should fail since we're reusing the same `sampleRefundItem` through `itemID: Int64 = 0`, right? I think we should remove the default parameters to force the actual IDs to differ and be able to test when they're the same vs different?

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift (hunk 1 above)
Comment (toupper) [reply Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift]: Good point, done in 3c081963d50c08cde59e9f1f7df1a34762ea4e60

File: Modules/Sources/Networking/Remote/RefundsRemote.swift (hunk 3 above)
Comment (toupper) [reply Modules/Sources/Networking/Remote/RefundsRemote.swift:156]: That comes from the open class `Remote`, and the enqueuing function

`public func enqueue<M: Mapper>(_ request: Request, mapper: M, completion: @escaping (M.Output?, Error?) -> Void)`

If we couldn't map it, we return nil there, and nil error.

File: Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift (hunk 4 above)
Comment (toupper) [reply Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift]: Nice catch, removed in 1fb5323d0bb32bb9f67531560a63284e832afa72

File: Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift (hunk 5 above)
Comment (toupper) [reply Modules/Sources/PointOfSale/Controllers/POSOrderListController.swift]: Good catch, removed in 0abe2f2bf5a647f7e3cc84e9c6935178a25dd024

File: Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift (hunk 11 above)
Comment (toupper) [reply Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift]: I looked into replacing waitUntil with `withObservationTracking` here. In this case the tests are asserting a side-effect (the refunds service being called) rather than an observable state change in the SUT, so Observation doesn’t fit well without adding extra test-only machinery to the mock.

For now, `waitUntil` keeps the tests simpler and explicit in my opinion.

Comment (toupper) [reply Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift]: On a second thought, I agree that waitUntil and timeouts are flaky, so I used continuations here 92259e8d0b9194a159fa99230c94369f0aeaa615

File: Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift (hunk 12 above)
Comment (toupper) [reply Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift:387]: ~~I removed that test as without waitUntil is quite complex to test, and the state change to loading is transitory and not so relevant in my opinion.~~

Edit: I decided to leave this with a refactored version of this waiting function, as any other approach makes it more complex or doesn't align to our needs. Refactored in 0d190a6a9a1c7d5d6e17a9d30f73405d0fa1aaed

File: Modules/Sources/NetworkingCore/Remote/POSRefundsRemoteProtocol.swift (hunk 6 above)
Comment (toupper) [reply Modules/Sources/NetworkingCore/Remote/POSRefundsRemoteProtocol.swift:4]: I was following the previous convention for POS remotes (see `POSOrdersRemoteProtocol`) for both cases. We can refactor it globally it we agree, but for now I think it is better to keep it the same way.

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderRefundCondensed.swift (hunk 8 above)
Comment (toupper) [reply Modules/Sources/Yosemite/PointOfSale/OrderList/POSOrderRefundCondensed.swift]: Good point, I firstly added that name as I expected to have POSOrderRefund, but that wasn't the case. I renamed in f18c5e93151fc8da09b3b9efef0d632aedb838f6

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundItem.swift (hunk 9 above)
Comment (toupper) [reply Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundItem.swift:6]: Good point. For now POS will only allow refunding full units, but I’d prefer to keep quantity as Decimal to stay consistent with the backend and avoid baking a temporary business rule into the model. We can enforce “whole units only” at the UI / validation layer and keep the model flexible for potential future fractional refunds.

File: Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundMapper.swift (hunk 10 above)
Comment (toupper) [reply Modules/Sources/Yosemite/PointOfSale/OrderList/POSRefundMapper.swift:6]: Same as above

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift (hunk 14 above)
Comment (toupper) [reply Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift:45]: I might be misunderstanding the concern, but I don’t think we need to handle duplicate refund IDs at this layer. This service assumes the backend contract guarantees valid data. If duplicate IDs are possible, that’s something we should clarify or fix at the backend / API contract level rather than adding defensive logic here.
The intention here is not to validate refund ID uniqueness, but simply to verify that when the remote succeeds, the service returns the same number of refunds it receives.

File: Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift (hunk 15 above)
Comment (toupper) [reply Modules/Tests/YosemiteTests/Tools/POS/POSRefundsServiceTests.swift:69]: I think this test has the same intent as the previous one: it’s only verifying that refund items are correctly mapped (productID, variationID, quantity), not that item IDs are unique or different.

Reusing the default itemID = 0 here is incidental, since itemID is not used by POSRefundsService nor asserted in this test. If we ever want to validate behavior around duplicate or distinct item IDs, that should be covered by a separate, explicit test with that specific intent.

File: Modules/Sources/TestKit/Testing+Helpers.swift (hunk 2 above)
Comment (toupper) [reply Modules/Sources/TestKit/Testing+Helpers.swift]: Good point! The main reason I added this helper is that these tests use the new Testing framework (not XCTest), and I wanted a small async-friendly utility we can use consistently here. I also refactored it to return a Bool so tests can explicitly #expect the condition is met (no fixed sleeps).

I agree about avoiding fixed waiting times. Where it made sense, I switched to an event-driven approach (awaitable mock via continuation) so we don’t poll at all. For the remaining cases, withObservationTracking wasn’t reliable / the state changes were too transitory, so waitForCondition was the simplest and most readable option for now.

**Comment by toupper** [comment]
> Just dropping a note about Xcode's odd behavior: While I seem able to build the target, when trying to run the tests I get compilation errors:

Thanks for the review and that note @iamgabrielma! I didn't see that, what Xcode version are you using?

**Comment by iamgabrielma** [comment]
> Thanks for the review and that note @iamgabrielma! I didn't see that, what Xcode version are you using?

I was using Xcode 16.2, after updating to 26.2 I haven't seen it anymore but it looked like a one-off anyway, perhaps some caching or whatever.

Thanks for the updates and the clarifications! LGTM ✅

**Comment by iamgabrielma** [comment]
(PD: Milestone is set to 24.0, in case you want to merge it earlier in 23.9 be sure to update it!)

**Review by iamgabrielma — APPROVED** [review]

File: Modules/Sources/TestKit/Testing+Helpers.swift [hunk 16]
```diff
@@ -0,0 +1,19 @@
+import Testing
+
+/// This file gathers helper functions for the new Testing framework
+
+public func waitForCondition(
```
Comment (staskus) [inline Modules/Sources/TestKit/Testing+Helpers.swift:5]: I may be nit-picky, but let's try not to use timeouts in our tests. PointOfSale tests can be super-quick, and artificial timeouts slow them down and cause flaky tests. For me, `PointOfSaleOrderListControllerTests` are randomly failing locally, and I think this may be a reason.

I remember addressing some of it previously
- https://github.com/woocommerce/woocommerce-ios/pull/16210
- https://github.com/woocommerce/woocommerce-ios/pull/16212

I will try to see locally if and how we can avoid using timeouts in this case for future reference. One thing we can do is start kicking off Claude/Agents instructions on how to write tests and try to guide them towards timeout avoidance.

Comment (staskus) [reply Modules/Sources/TestKit/Testing+Helpers.swift:5]: More context. These are the failures I got:

```swift
 /Users/povilasstaskus/Projects/woocommerce-ios-woomob-2028-support-card-reader-auto-reconnection/Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift
  /Users/povilasstaskus/Projects/woocommerce-ios-woomob-2028-support-card-reader-auto-reconnection/Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift:438
  selectOrder_when_provides_refunds_then_updates_refunds_state_with_results(): Expectation failed: didLoad: Expected selectedOrderRefundsState to become .loaded before timeout

  /Users/povilasstaskus/Projects/woocommerce-ios-woomob-2028-support-card-reader-auto-reconnection/Modules/Tests/PointOfSaleTests/Controllers/POSOrderListControllerTests.swift:537
  refundActionAvailability_when_refunds_failed_then_unavailable(): Expectation failed: didFail
 ```

since the timeout is generous for this type of issue, it's almost never reproducible. I was running the whole suite of tests, maybe some other processes stalled the machine to get these failures.

----
 
 I looked at the code, and I understand the challenge. Excuse me for jumping to conclusions too quickly. There are no perfect options here. I provide more explanations here https://github.com/woocommerce/woocommerce-ios/pull/16602. Let me know if it makes sense to you to move from manual polling to `withObservationTracking`.

Comment (toupper) [reply Modules/Sources/TestKit/Testing+Helpers.swift:5]: Awesome! Thanks for sharing more context @staskus. Agree that `withObservationTracking` is more robust for this case, so if possible, it's the way to go. Let's add more analysis to that PR, and thanks a lot for working on this
