### PR TITLE
Fix trunk build: conform IsolationCapturingNetwork to Network

### PR DESCRIPTION
**Pull request by toupper**
## What

Adds `usesJetpackTunnel(for:)` to the test-only `IsolationCapturingNetwork` in `RemoteTests`.

## Why

Trunk does not build since #17877 merged. That PR added `usesJetpackTunnel(for:)` to the `Network` protocol, and trunk already had `IsolationCapturingNetwork` from the network isolation work. Each branch was green on its own, but the merge left the double without the new requirement, so `NetworkingTests` fails to compile:

```
RemoteTests.swift:1703: error: type 'IsolationCapturingNetwork' does not conform to protocol 'Network'
```

## How

Same implementation as the other doubles in the file: `request is JetpackRequest`.

## Test Steps

- CI Build job goes green.
- `NetworkingTests/RemoteTests` passes (66 tests locally).

---
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-ios/milestone/288">25.7</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
